//
//  File.swift
//  
//
//  Created by Nikola Derikonjic on 16.7.23..
//

import Foundation

//
// UserAdventureLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum AdventureLanguageEnum: Int, Codable, CaseIterable {
    case German
    case   French
    case  Italian
    case  English
    case  Russian
    case  Dansk
    case  Spanish
    case  Montenegro
    case  Serbian
    case  Slovenian
    case  Magyar
    case  Czech
    case Dutch
    case  Chinesses
    case  Norwegian
}

