//
// AdventuresQueryAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class AdventuresQueryAllOf: Codable, JSONEncodable, Hashable {

    public var all: Bool?
    public var recommended: Bool?
    public var fields: AdventuresQueryFields?

    public init(all: Bool? = nil, recommended: Bool? = nil, fields: AdventuresQueryFields? = nil) {
        self.all = all
        self.recommended = recommended
        self.fields = fields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case all
        case recommended
        case fields
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(all, forKey: .all)
        try container.encodeIfPresent(recommended, forKey: .recommended)
        try container.encodeIfPresent(fields, forKey: .fields)
    }

    public static func == (lhs: AdventuresQueryAllOf, rhs: AdventuresQueryAllOf) -> Bool {
        lhs.all == rhs.all &&
        lhs.recommended == rhs.recommended &&
        lhs.fields == rhs.fields
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(all?.hashValue)
        hasher.combine(recommended?.hashValue)
        hasher.combine(fields?.hashValue)
        
    }
}

