//
// AdventurCategoryLightModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class AdventurCategoryLightModel: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var title: String?
    public var icon: String?
    public var lang: AdventureLanguageEnum
    public var translations: [String:String]
    public var catTranslation: String?

    public init(lang: AdventureLanguageEnum, translations: [String:String], id: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, title: String? = nil, icon: String? = nil, catTranslation: String? = nil) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.title = title
        self.icon = icon
        self.lang = lang
        self.translations = translations
        self.catTranslation = catTranslation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt
        case updatedAt
        case title
        case icon
        case lang
        case translations
        case catTranslation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(lang, forKey: .lang)
        try container.encodeIfPresent(translations, forKey: .translations)
        try container.encodeIfPresent(catTranslation, forKey: .catTranslation)
    }

    public static func == (lhs: AdventurCategoryLightModel, rhs: AdventurCategoryLightModel) -> Bool {
        lhs.id == rhs.id &&
        lhs.createdAt == rhs.createdAt &&
        lhs.updatedAt == rhs.updatedAt &&
        lhs.title == rhs.title &&
        lhs.lang == rhs.lang &&
        lhs.translations == rhs.translations &&
        lhs.catTranslation == rhs.catTranslation &&
        lhs.icon == rhs.icon
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id?.hashValue)
        hasher.combine(createdAt?.hashValue)
        hasher.combine(updatedAt?.hashValue)
        hasher.combine(title?.hashValue)
        hasher.combine(icon?.hashValue)
        hasher.combine(catTranslation?.hashValue)
        hasher.combine(translations.hashValue)
        hasher.combine(lang.hashValue)
        
    }
}

