//
// AdventureLightModelMediaInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class AdventureLightModelMediaInfo: Codable, JSONEncodable, Hashable {

    public var photos: [AdventurePhoto]?
    public var videos: [String]?
    public var text: String?

    public init(photos: [AdventurePhoto]? = nil, videos: [String]? = nil, text: String? = nil) {
        self.photos = photos
        self.videos = videos
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case photos
        case videos
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(photos, forKey: .photos)
        try container.encodeIfPresent(videos, forKey: .videos)
        try container.encodeIfPresent(text, forKey: .text)
    }

    public static func == (lhs: AdventureLightModelMediaInfo, rhs: AdventureLightModelMediaInfo) -> Bool {
        lhs.photos == rhs.photos &&
        lhs.videos == rhs.videos &&
        lhs.text == rhs.text
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(photos?.hashValue)
        hasher.combine(videos?.hashValue)
        hasher.combine(text?.hashValue)
        
    }
}

