//
// AdventuresLightModelAllOfCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AdventuresLightModelAllOfCategory: Codable, JSONEncodable, Hashable {
    case typeAdventurCategoryLightModel(AdventurCategoryLightModel)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeAdventurCategoryLightModel(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AdventurCategoryLightModel.self) {
            self = .typeAdventurCategoryLightModel(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of AdventuresLightModelAllOfCategory"))
        }
    }
}

