//
// AdventurCategoryLightModelAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class AdventurCategoryLightModelAllOf: Codable, JSONEncodable, Hashable {

    public var title: String?
    public var icon: String?

    public init(title: String? = nil, icon: String? = nil) {
        self.title = title
        self.icon = icon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case icon
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(icon, forKey: .icon)
    }

    public static func == (lhs: AdventurCategoryLightModelAllOf, rhs: AdventurCategoryLightModelAllOf) -> Bool {
        lhs.title == rhs.title &&
        lhs.icon == rhs.icon
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(title?.hashValue)
        hasher.combine(icon?.hashValue)
        
    }
}

