//
// AdventuresQueryFields.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum AdventuresQueryFields: Int, Codable {
    
    case GeoInfo = 0
    case UserInfo = 1
    case MediaInfo = 3
    case All = -1
}

enum AdventuresQueryFieldsBitwise: Int {
    case GeoInfo, UserInfo, MediaInfo, All = -1
    func bitmask() -> UInt32 {
        return 1 << self.rawValue
      }
  }
