//
// UserAdventureLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum BookmarkType: Int, Codable, CaseIterable {
    case Adventure = 0
    case User = 1
}
