//
// CountryModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CountryModel: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var name: String?
    public var geom: AnyCodable?
    public var polygons: AnyCodable?

    public init(id: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, name: String? = nil, geom: AnyCodable? = nil, polygons: AnyCodable? = nil) {
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.name = name
        self.geom = geom
        self.polygons = polygons
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case createdAt
        case updatedAt
        case name
        case geom
        case polygons
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(geom, forKey: .geom)
        try container.encodeIfPresent(polygons, forKey: .polygons)
    }
}

