//
// EntitySearchResultOfUserProfileActivityAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class EntitySearchResultOfUserProfileActivityAllOf: Codable, JSONEncodable, Hashable {

    public var entityCounts: EntityCounts?

    public init(entityCounts: EntityCounts? = nil) {
        self.entityCounts = entityCounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entityCounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(entityCounts, forKey: .entityCounts)
    }

    public static func == (lhs: EntitySearchResultOfUserProfileActivityAllOf, rhs: EntitySearchResultOfUserProfileActivityAllOf) -> Bool {
        lhs.entityCounts == rhs.entityCounts
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(entityCounts?.hashValue)
        
    }
}

