//
// SearchQueryRangeOfDateTime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class SearchQueryRangeOfDateTime: Codable, JSONEncodable, Hashable {

    public var min: Date?
    public var max: Date?

    public init(min: Date? = nil, max: Date? = nil) {
        self.min = min
        self.max = max
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case min
        case max
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(min, forKey: .min)
        try container.encodeIfPresent(max, forKey: .max)
    }

    public static func == (lhs: SearchQueryRangeOfDateTime, rhs: SearchQueryRangeOfDateTime) -> Bool {
        lhs.min == rhs.min &&
        lhs.max == rhs.max
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(min?.hashValue)
        hasher.combine(max?.hashValue)
        
    }
}

