//
// AdventuresQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class SearchSuggestionResponseCountry: Codable, JSONEncodable, Hashable {
    public var id: String
    public var name: String
   
    
    
    public init(id: String, name: String) {
        self.id = id
        self.name = name
        
        
       
        
    }
    
    
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
       
       
        
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        

        
        
    }
    
    public static func == (lhs: SearchSuggestionResponseCountry, rhs: SearchSuggestionResponseCountry) -> Bool {
        lhs.id == rhs.id &&
        lhs.name == rhs.name
        
        
    }
    
    public func hash(into hasher: inout Hasher) {
        hasher.combine(id.hashValue)
        hasher.combine(name.hashValue)
        
        
        
        
        
    }
    
}
