//
// AdventuresQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class SearchSuggestionResponseAdventure: Codable, JSONEncodable, Hashable {
    public var id: String
    public var title: String
    public var coverPhotoId: String
    public var subtitle: String
    
    
    public init(id: String, title: String, coverPhotoId: String, subtitle: String) {
        self.id = id
        self.title = title
        self.coverPhotoId = coverPhotoId
        self.subtitle = subtitle
        
       
        
    }
    
    
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case coverPhotoId
        case subtitle
        
       
        
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(coverPhotoId, forKey: .coverPhotoId)
        try container.encodeIfPresent(subtitle, forKey: .subtitle)

        
        
    }
    
    public static func == (lhs: SearchSuggestionResponseAdventure, rhs: SearchSuggestionResponseAdventure) -> Bool {
        lhs.id == rhs.id &&
        lhs.title == rhs.title &&
        lhs.coverPhotoId == rhs.coverPhotoId &&
        lhs.subtitle == rhs.subtitle
        
        
    }
    
    public func hash(into hasher: inout Hasher) {
        hasher.combine(id.hashValue)
        hasher.combine(title.hashValue)
        hasher.combine(coverPhotoId.hashValue)
        hasher.combine(subtitle.hashValue)
        
        
        
        
    }
    
}
