//
// AdventuresQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class SearchSuggestionResponseUser: Codable, JSONEncodable, Hashable {
    public var id: String
    public var name: String
    public var title: String
    public var photoId: String
    
    public init(id: String, name: String, title: String, photoId: String) {
        self.id = id
        self.name = name
        self.title = title
        self.photoId = photoId
       
        
    }
    
    
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case title
        case photoId
       
        
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(photoId, forKey: .photoId)
        
        
    }
    
    public static func == (lhs: SearchSuggestionResponseUser, rhs: SearchSuggestionResponseUser) -> Bool {
        lhs.id == rhs.id &&
        lhs.name == rhs.name &&
        lhs.title == rhs.title &&
        lhs.photoId == rhs.photoId
        
        
    }
    
    public func hash(into hasher: inout Hasher) {
        hasher.combine(id.hashValue)
        hasher.combine(name.hashValue)
        hasher.combine(title.hashValue)
        hasher.combine(photoId.hashValue)
        
        
        
    }
    
}
