//
// AdventuresQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class SearchSuggestionResponseCategory: Codable, JSONEncodable, Hashable {
    public var id: String
    public var name: String
    public var icon: String
    
    
    public init(id: String, name: String, icon: String) {
        self.id = id
        self.name = name
        self.icon = icon
        
       
        
    }
    
    
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case icon
        
       
        
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(icon, forKey: .icon)

        
        
    }
    
    public static func == (lhs: SearchSuggestionResponseCategory, rhs: SearchSuggestionResponseCategory) -> Bool {
        lhs.id == rhs.id &&
        lhs.name == rhs.name &&
        lhs.icon == rhs.icon
        
        
    }
    
    public func hash(into hasher: inout Hasher) {
        hasher.combine(id.hashValue)
        hasher.combine(name.hashValue)
        hasher.combine(icon.hashValue)
        
        
        
        
    }
    
}
