//
// TextSearchQueryAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class TextSearchQueryAllOf: Codable, JSONEncodable, Hashable {

    static let textRule = StringRule(minLength: 0, maxLength: 200, pattern: nil)
    public var text: String?

    public init(text: String? = nil) {
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(text, forKey: .text)
    }

    public static func == (lhs: TextSearchQueryAllOf, rhs: TextSearchQueryAllOf) -> Bool {
        lhs.text == rhs.text
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(text?.hashValue)
        
    }
}

