//
// AdventuresQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class UserAdventureProfile: Codable, JSONEncodable, Hashable {

    
    public var profile: UserModel
    
    public var adventures: [AdventuresLightModel]
    public var stats: UserAdventureProfileStats
    
   

    public init(
        profile: UserModel,
        
        adventures: [AdventuresLightModel],
        stats: UserAdventureProfileStats
    ) {
        self.profile = profile
        self.adventures = adventures
        self.stats = stats
        
        
        
        
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case profile
        case adventures
        case stats
        
        
        
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(profile, forKey: .profile)
        try container.encodeIfPresent(adventures, forKey: .adventures)
        try container.encodeIfPresent(stats, forKey: .stats)
        
        
        
    }

    public static func == (lhs: UserAdventureProfile, rhs: UserAdventureProfile) -> Bool {
        lhs.profile == rhs.profile &&
        lhs.stats == rhs.stats &&
        lhs.adventures == rhs.adventures
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(profile.hashValue)
        hasher.combine(adventures.hashValue)
        hasher.combine(stats.hashValue)
        
        
        
        
    }
}
