//
// UserContextModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class UserContextModel: Codable, JSONEncodable, Hashable {

    public var identity: AdventuresLightModelAllOfUserProfile?
    public var access: UserContextModelAccess?

    public init(identity: AdventuresLightModelAllOfUserProfile? = nil, access: UserContextModelAccess? = nil) {
        self.identity = identity
        self.access = access
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case identity
        case access
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(identity, forKey: .identity)
        try container.encodeIfPresent(access, forKey: .access)
    }

    public static func == (lhs: UserContextModel, rhs: UserContextModel) -> Bool {
        lhs.identity == rhs.identity &&
        lhs.access == rhs.access
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(identity?.hashValue)
        hasher.combine(access?.hashValue)
        
    }
}

