//
// UserDeviceType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum UserDeviceType: Int, Codable, CaseIterable {
    case Android = 0
    case Iphone = 1
    case Desktop = 2
}
