//
// UserGlobalPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class UserGlobalPermissions: Codable, JSONEncodable, Hashable {

    public var users: UserGlobalPermissionsUsers?

    public init(users: UserGlobalPermissionsUsers? = nil) {
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(users, forKey: .users)
    }

    public static func == (lhs: UserGlobalPermissions, rhs: UserGlobalPermissions) -> Bool {
        lhs.users == rhs.users
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(users?.hashValue)
        
    }
}

