//
// UserAdventureLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum UserAdventureLevel: Int, Codable, CaseIterable {
    case Easy = 0
    case Moderate = 1
    case Hard = 2
}
