//
// UserAccessInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class UserAccessInfo: Codable, JSONEncodable, Hashable {

    public var globalPermissions: UserAccessInfoGlobalPermissions?

    public init(globalPermissions: UserAccessInfoGlobalPermissions? = nil) {
        self.globalPermissions = globalPermissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case globalPermissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(globalPermissions, forKey: .globalPermissions)
    }

    public static func == (lhs: UserAccessInfo, rhs: UserAccessInfo) -> Bool {
        lhs.globalPermissions == rhs.globalPermissions
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(globalPermissions?.hashValue)
        
    }
}

