//
// UserRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum UserRole: Int, Codable, CaseIterable {
    case RegularUser = 0
    case Admin = 1
}
