//
// UserCredentialOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public final class UserCredentialOptions: Codable, JSONEncodable, Hashable {

    public var persistent: Bool?

    public init(persistent: Bool? = nil) {
        self.persistent = persistent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case persistent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(persistent, forKey: .persistent)
    }

    public static func == (lhs: UserCredentialOptions, rhs: UserCredentialOptions) -> Bool {
        lhs.persistent == rhs.persistent
        
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(persistent?.hashValue)
        
    }
}

